baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hyde"
title = "Kemikal Solutions"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = true
theme = "hyde"
themeColor = ""
